url: bedroesb.github.io
baseurl: /rdm-toolkit
repository: https://github.com/bedroesb/rdm-toolkit

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: RDM Toolkit
# this appears on the top navigation bar next to the home button

site_title: ELIXIR Data Management Toolkit
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: ELIXIR Converge
# this appears in the page_ending

github_editme_path: bedroesb/rdm-toolkit/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# google_analytics: UA-66296557-1
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor
  - CODEOWNERS
  - var/
  - README.md

feedback_subject_line: RDM toolkit

feedback_email: example@gmail.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

feedback_text: "Give feedback"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: main
      topnav: topnav

sidebars:
- main
- contribute

description: "This website will need a description"

github: [metadata]

RDM_pages: ["/re-using.html", "/preserving.html", "/analysing.html", "/processing.html", "/planning.html", "/collecting.html", "/sharing.html"]
